services:
  backend:
    image: dacaldes/pairup-backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: pairup-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
